include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    file_names: false
    prefer_const_constructors: false
    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
    prefer_void_to_null: false
    avoid_renaming_method_parameters: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    prefer_interpolation_to_compose_strings: false
